/**
 * Codex runtime for the NanoClaw agent container.
 *
 * Alternative to the Claude Agent SDK path in index.ts, selected when
 * NANOCLAW_RUNTIME=codex. Drives the OpenAI Codex CLI (`codex exec --json`) one
 * turn per message, resuming the same Codex session for follow-ups. It reuses the
 * provider-neutral IPC/output primitives from index.ts (passed in as `deps`) so the
 * host sees the identical OUTPUT_START/END marker protocol.
 *
 * Codex event schema (codex exec --json), verified against codex-cli 0.142.5:
 *   {"type":"thread.started","thread_id":"<session id>"}
 *   {"type":"turn.started"}
 *   {"type":"item.completed","item":{"type":"agent_message","text":"..."}}
 *   {"type":"turn.completed","usage":{...}}
 */
import fs from 'fs';
import path from 'path';
import { spawn } from 'child_process';

interface ContainerOutput {
  status: 'success' | 'error';
  result: string | null;
  newSessionId?: string;
  error?: string;
}

export interface CodexDeps {
  writeOutput: (output: ContainerOutput) => void;
  waitForIpcMessage: () => Promise<string | null>;
  log: (message: string) => void;
}

interface CodexContainerInput {
  chatJid: string;
  groupFolder: string;
  isMain: boolean;
}

const CODEX_HOME = process.env.CODEX_HOME || '/home/node/.codex';
const WORKDIR = '/workspace/group';

/** JSON.stringify doubles as a valid TOML basic-string encoder for our values. */
function toml(value: string): string {
  return JSON.stringify(value);
}

/**
 * Write ~/.codex/config.toml wiring the same stdio MCP server(s) the Claude path
 * uses, and disabling Codex's own sandbox/approvals (the container already isolates).
 */
function writeCodexConfig(
  mcpServerPath: string,
  input: CodexContainerInput,
): void {
  fs.mkdirSync(CODEX_HOME, { recursive: true });
  let config = `# Generated by NanoClaw agent-runner (codex runtime) — regenerated each spawn.
approval_policy = "never"
sandbox_mode = "danger-full-access"

[mcp_servers.nanoclaw]
command = "node"
args = [${toml(mcpServerPath)}]

[mcp_servers.nanoclaw.env]
NANOCLAW_CHAT_JID = ${toml(input.chatJid)}
NANOCLAW_GROUP_FOLDER = ${toml(input.groupFolder)}
NANOCLAW_IS_MAIN = ${toml(input.isMain ? '1' : '0')}
`;

  // Google Calendar MCP — only when its stub creds are mounted. Codex does NOT pass
  // the parent env to MCP subprocesses, so the OneCLI gateway proxy/CA vars must be
  // listed explicitly here (unlike the Claude path's `...process.env`); otherwise the
  // Google OAuth refresh bypasses the gateway and fails with invalid_client. The
  // undici proxy-preload forces Node 22's fetch through the gateway.
  const gcalCreds = '/home/node/.config/google-calendar-mcp/gcp-oauth.keys.json';
  if (fs.existsSync(gcalCreds)) {
    const gcalEnv: Record<string, string> = {
      NODE_OPTIONS: '--import=file:///app/proxy-preload.mjs',
      GOOGLE_OAUTH_CREDENTIALS: gcalCreds,
      GOOGLE_CALENDAR_MCP_TOKEN_PATH:
        '/home/node/.config/google-calendar-mcp/tokens.json',
    };
    for (const key of [
      'HTTPS_PROXY',
      'HTTP_PROXY',
      'https_proxy',
      'http_proxy',
      'NODE_EXTRA_CA_CERTS',
      'SSL_CERT_FILE',
      'NO_PROXY',
      'no_proxy',
    ]) {
      const v = process.env[key];
      if (v) gcalEnv[key] = v;
    }
    config += `\n[mcp_servers.gcal]\ncommand = "google-calendar-mcp"\n\n[mcp_servers.gcal.env]\n`;
    for (const [k, v] of Object.entries(gcalEnv)) {
      config += `${k} = ${toml(v)}\n`;
    }
  }

  fs.writeFileSync(path.join(CODEX_HOME, 'config.toml'), config);
}

/**
 * Codex reads AGENTS.md (not CLAUDE.md). Surface the group's memory by symlinking
 * AGENTS.md -> CLAUDE.md in the workspace so `codex` picks it up from cwd.
 */
function surfaceGroupMemory(deps: CodexDeps): void {
  const claudeMd = path.join(WORKDIR, 'CLAUDE.md');
  const agentsMd = path.join(WORKDIR, 'AGENTS.md');
  if (!fs.existsSync(claudeMd) || fs.existsSync(agentsMd)) return;
  try {
    fs.symlinkSync('CLAUDE.md', agentsMd);
  } catch (err) {
    // Fall back to a copy if symlinks aren't permitted on the mount.
    try {
      fs.copyFileSync(claudeMd, agentsMd);
    } catch {
      deps.log(
        `Could not surface CLAUDE.md as AGENTS.md: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }
}

interface CodexTurnResult {
  sessionId?: string;
  result: string | null;
}

/** Run one `codex exec` (or `codex exec resume`) turn and parse its JSONL stream. */
function runCodexTurn(
  prompt: string,
  sessionId: string | undefined,
  deps: CodexDeps,
): Promise<CodexTurnResult> {
  return new Promise((resolve, reject) => {
    const flags = [
      '--json',
      '--skip-git-repo-check',
      '--sandbox',
      'danger-full-access',
    ];
    const args = sessionId
      ? ['exec', 'resume', sessionId, ...flags, prompt]
      : ['exec', ...flags, prompt];

    // stdin 'ignore' → immediate EOF, so codex doesn't hang "Reading additional
    // input from stdin...". Inherit env (proxy/CA vars + CODEX_HOME).
    const child = spawn('codex', args, {
      cwd: WORKDIR,
      stdio: ['ignore', 'pipe', 'pipe'],
      env: process.env,
    });

    let buf = '';
    let newSessionId: string | undefined;
    const agentMessages: string[] = [];
    let turnCompleted = false;

    const handleLine = (line: string): void => {
      const trimmed = line.trim();
      if (!trimmed) return;
      let ev: {
        type?: string;
        thread_id?: string;
        item?: { type?: string; text?: string };
      };
      try {
        ev = JSON.parse(trimmed);
      } catch {
        return; // non-JSON line (banner/warning)
      }
      if (ev.type === 'thread.started' && ev.thread_id) {
        newSessionId = ev.thread_id;
      } else if (
        ev.type === 'item.completed' &&
        ev.item?.type === 'agent_message' &&
        typeof ev.item.text === 'string'
      ) {
        agentMessages.push(ev.item.text);
      } else if (ev.type === 'turn.completed') {
        turnCompleted = true;
      }
    };

    child.stdout.on('data', (d: Buffer) => {
      buf += d.toString();
      let idx: number;
      while ((idx = buf.indexOf('\n')) !== -1) {
        handleLine(buf.slice(0, idx));
        buf = buf.slice(idx + 1);
      }
    });
    child.stderr.on('data', (d: Buffer) => {
      const s = d.toString().trim();
      if (s) deps.log(`[codex] ${s.slice(0, 300)}`);
    });
    child.on('error', reject);
    child.on('close', (code) => {
      if (buf) handleLine(buf); // flush any trailing partial line
      // The last agent_message is the user-facing reply.
      const result = agentMessages.length
        ? agentMessages[agentMessages.length - 1]
        : null;
      if (code !== 0 && !turnCompleted) {
        reject(new Error(`codex exited with code ${code}`));
        return;
      }
      resolve({ sessionId: newSessionId, result });
    });
  });
}

/**
 * Codex equivalent of the Claude query loop: one turn per message, resuming the
 * session for follow-ups, blocking on IPC between turns. Emits results via the
 * shared writeOutput markers so the host handles them identically to the Claude path.
 */
export async function runCodexLoop(
  initialPrompt: string,
  initialSessionId: string | undefined,
  containerInput: CodexContainerInput,
  mcpServerPath: string,
  deps: CodexDeps,
): Promise<void> {
  writeCodexConfig(mcpServerPath, containerInput);
  surfaceGroupMemory(deps);

  let sessionId = initialSessionId;
  let prompt = initialPrompt;

  while (true) {
    deps.log(`Codex turn (session: ${sessionId || 'new'})`);
    let turn: CodexTurnResult;
    try {
      turn = await runCodexTurn(prompt, sessionId, deps);
    } catch (err) {
      // A stale session id from a previous container can't resume — start fresh once.
      if (sessionId) {
        deps.log(
          `Codex resume failed (${err instanceof Error ? err.message : String(err)}); starting a fresh session`,
        );
        sessionId = undefined;
        turn = await runCodexTurn(prompt, undefined, deps);
      } else {
        throw err;
      }
    }

    if (turn.sessionId) sessionId = turn.sessionId;
    deps.log(
      `Codex turn done (session: ${sessionId || 'none'}, result: ${turn.result ? `${turn.result.slice(0, 120)}` : 'none'})`,
    );

    // Emit the reply, then a null session-update (mirrors the Claude outer loop:
    // keeps the host's session tracking + idle timer consistent).
    deps.writeOutput({
      status: 'success',
      result: turn.result,
      newSessionId: sessionId,
    });
    deps.writeOutput({ status: 'success', result: null, newSessionId: sessionId });

    const next = await deps.waitForIpcMessage();
    if (next === null) {
      deps.log('Close sentinel received, exiting codex loop');
      break;
    }
    prompt = next;
  }
}
