/**
 * Grok runtime for the NanoClaw agent container.
 *
 * Alternative to the Claude Agent SDK path in index.ts, selected when
 * NANOCLAW_RUNTIME=grok. Drives the Grok Build CLI (`grok -p --output-format json`)
 * one turn per message, resuming the same Grok session for follow-ups. It reuses the
 * provider-neutral IPC/output primitives from index.ts (passed in as `deps`) so the
 * host sees the identical OUTPUT_START/END marker protocol.
 *
 * Headless JSON shape (verified against Grok Build 1.0.0 docs):
 *   success: { "text": "...", "sessionId": "...", "stopReason": "end_turn", ... }
 *   error:   { "type": "error", "message": "..." }  (non-zero exit)
 */
import fs from 'fs';
import path from 'path';
import { spawn } from 'child_process';
import { buildGrokMcpConfigToml, toml } from './mcp-servers.js';

interface ContainerOutput {
  status: 'success' | 'error';
  result: string | null;
  newSessionId?: string;
  error?: string;
}

export interface GrokDeps {
  writeOutput: (output: ContainerOutput) => void;
  waitForIpcMessage: () => Promise<string | null>;
  log: (message: string) => void;
}

interface GrokContainerInput {
  chatJid: string;
  groupFolder: string;
  isMain: boolean;
  agentSettings?: RuntimeAgentSettings;
}

interface RuntimeAgentSettings {
  model?: string;
  reasoningEffort?: string;
}

const GROK_HOME = process.env.GROK_HOME || '/home/node/.grok';
const WORKDIR = '/workspace/group';
const GROK_REASONING_EFFORTS = [
  'none',
  'minimal',
  'low',
  'medium',
  'high',
  'xhigh',
  'max',
] as const;
type GrokReasoningEffort = (typeof GROK_REASONING_EFFORTS)[number];

function isGrokReasoningEffort(
  effort: string | undefined,
): effort is GrokReasoningEffort {
  return GROK_REASONING_EFFORTS.includes(effort as GrokReasoningEffort);
}

function grokSettingArgs(settings: RuntimeAgentSettings | undefined): string[] {
  const args: string[] = [];
  if (settings?.model) {
    args.push('-m', settings.model);
  }
  if (isGrokReasoningEffort(settings?.reasoningEffort)) {
    args.push('--reasoning-effort', settings.reasoningEffort);
  }
  return args;
}

/**
 * Write ~/.grok/config.toml wiring the same stdio MCP servers the Claude/Codex
 * paths use, and forcing always-approve so the container is the isolation boundary.
 * Also seeds folder trust for the workspace so project MCP is not gated.
 */
function writeGrokConfig(
  mcpServerPath: string,
  input: GrokContainerInput,
): void {
  fs.mkdirSync(GROK_HOME, { recursive: true });

  let config = `# Generated by NanoClaw agent-runner (grok runtime) — regenerated each spawn.
[cli]
auto_update = false

[ui]
permission_mode = "always-approve"

[features]
telemetry = false
`;

  if (input.agentSettings?.model) {
    config += `
[models]
default = ${toml(input.agentSettings.model)}
`;
  }

  config += `
[mcp_servers.nanoclaw]
command = "node"
args = [${toml(mcpServerPath)}]
enabled = true

[mcp_servers.nanoclaw.env]
NANOCLAW_CHAT_JID = ${toml(input.chatJid)}
NANOCLAW_GROUP_FOLDER = ${toml(input.groupFolder)}
NANOCLAW_IS_MAIN = ${toml(input.isMain ? '1' : '0')}
`;

  config += buildGrokMcpConfigToml();

  fs.writeFileSync(path.join(GROK_HOME, 'config.toml'), config);

  // Pre-trust the group workspace so headless mode does not block project tools/rules.
  // Format matches Grok's trusted_folders.toml store.
  const trustPath = path.join(GROK_HOME, 'trusted_folders.toml');
  const decidedAt = Math.floor(Date.now() / 1000);
  const trustConfig = `# Generated by NanoClaw agent-runner (grok runtime)
[folders.${toml(WORKDIR)}]
trusted = true
decided_at = ${decidedAt}
`;
  fs.writeFileSync(trustPath, trustConfig);
}

/**
 * Grok reads AGENTS.md (and project rules). Surface the group's memory by
 * symlinking AGENTS.md -> CLAUDE.md in the workspace when needed.
 */
function surfaceGroupMemory(deps: GrokDeps): void {
  const claudeMd = path.join(WORKDIR, 'CLAUDE.md');
  const agentsMd = path.join(WORKDIR, 'AGENTS.md');
  if (!fs.existsSync(claudeMd) || fs.existsSync(agentsMd)) return;
  try {
    fs.symlinkSync('CLAUDE.md', agentsMd);
  } catch (err) {
    try {
      fs.copyFileSync(claudeMd, agentsMd);
    } catch {
      deps.log(
        `Could not surface CLAUDE.md as AGENTS.md: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }
}

interface GrokTurnResult {
  sessionId?: string;
  result: string | null;
}

class GrokHeadlessError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'GrokHeadlessError';
  }
}

function interpretGrokJsonObject(obj: {
  type?: string;
  message?: string;
  text?: string;
  sessionId?: string;
}): GrokTurnResult | null {
  if (obj.type === 'error') {
    throw new GrokHeadlessError(obj.message || 'Grok headless error');
  }
  if (typeof obj.text === 'string' || typeof obj.sessionId === 'string') {
    return {
      result: typeof obj.text === 'string' ? obj.text : null,
      sessionId: typeof obj.sessionId === 'string' ? obj.sessionId : undefined,
    };
  }
  return null;
}

/** Parse headless --output-format json stdout into text + sessionId. */
export function parseGrokJsonOutput(stdout: string): GrokTurnResult {
  const trimmed = stdout.trim();
  if (!trimmed) {
    return { result: null };
  }

  // Prefer the last JSON object if banners/warnings precede it.
  const lines = trimmed
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);
  for (let i = lines.length - 1; i >= 0; i--) {
    try {
      const obj = JSON.parse(lines[i]) as {
        type?: string;
        message?: string;
        text?: string;
        sessionId?: string;
      };
      const interpreted = interpretGrokJsonObject(obj);
      if (interpreted) return interpreted;
    } catch (err) {
      if (err instanceof GrokHeadlessError) throw err;
      // not JSON on this line — keep scanning
    }
  }

  try {
    const obj = JSON.parse(trimmed) as {
      type?: string;
      message?: string;
      text?: string;
      sessionId?: string;
    };
    const interpreted = interpretGrokJsonObject(obj);
    if (interpreted) return interpreted;
  } catch (err) {
    if (err instanceof GrokHeadlessError) throw err;
  }

  // Non-JSON fallback: treat entire stdout as the reply.
  return { result: trimmed };
}

/** Run one `grok -p` turn and parse its JSON result. */
function runGrokTurn(
  prompt: string,
  sessionId: string | undefined,
  agentSettings: RuntimeAgentSettings | undefined,
  deps: GrokDeps,
): Promise<GrokTurnResult> {
  return new Promise((resolve, reject) => {
    const args = [
      '-p',
      prompt,
      '--output-format',
      'json',
      '--always-approve',
      '--no-auto-update',
      '--cwd',
      WORKDIR,
      ...grokSettingArgs(agentSettings),
    ];
    if (sessionId) {
      args.push('-r', sessionId);
    }

    // stdin 'ignore' → immediate EOF. Inherit env (proxy/CA vars + GROK_HOME).
    const child = spawn('grok', args, {
      cwd: WORKDIR,
      stdio: ['ignore', 'pipe', 'pipe'],
      env: process.env,
    });

    let stdout = '';
    let stderr = '';

    child.stdout.on('data', (d: Buffer) => {
      stdout += d.toString();
    });
    child.stderr.on('data', (d: Buffer) => {
      const s = d.toString();
      stderr += s;
      const trimmed = s.trim();
      if (trimmed) deps.log(`[grok] ${trimmed.slice(0, 300)}`);
    });
    child.on('error', reject);
    child.on('close', (code) => {
      try {
        const parsed = parseGrokJsonOutput(stdout);
        if (code !== 0 && !parsed.result) {
          reject(
            new Error(
              `grok exited with code ${code}${stderr.trim() ? `: ${stderr.trim().slice(0, 200)}` : ''}`,
            ),
          );
          return;
        }
        resolve(parsed);
      } catch (err) {
        reject(err instanceof Error ? err : new Error(String(err)));
      }
    });
  });
}

/**
 * Grok equivalent of the Claude/Codex query loop: one turn per message, resuming
 * the session for follow-ups, blocking on IPC between turns.
 */
export async function runGrokLoop(
  initialPrompt: string,
  initialSessionId: string | undefined,
  containerInput: GrokContainerInput,
  mcpServerPath: string,
  deps: GrokDeps,
): Promise<void> {
  writeGrokConfig(mcpServerPath, containerInput);
  surfaceGroupMemory(deps);

  let sessionId = initialSessionId;
  let prompt = initialPrompt;

  while (true) {
    deps.log(`Grok turn (session: ${sessionId || 'new'})`);
    let turn: GrokTurnResult;
    try {
      turn = await runGrokTurn(
        prompt,
        sessionId,
        containerInput.agentSettings,
        deps,
      );
    } catch (err) {
      // A stale session id from a previous container can't resume — start fresh once.
      if (sessionId) {
        deps.log(
          `Grok resume failed (${err instanceof Error ? err.message : String(err)}); starting a fresh session`,
        );
        sessionId = undefined;
        turn = await runGrokTurn(
          prompt,
          undefined,
          containerInput.agentSettings,
          deps,
        );
      } else {
        throw err;
      }
    }

    if (turn.sessionId) sessionId = turn.sessionId;
    deps.log(
      `Grok turn done (session: ${sessionId || 'none'}, result: ${turn.result ? `${turn.result.slice(0, 120)}` : 'none'})`,
    );

    deps.writeOutput({
      status: 'success',
      result: turn.result,
      newSessionId: sessionId,
    });
    deps.writeOutput({
      status: 'success',
      result: null,
      newSessionId: sessionId,
    });

    const next = await deps.waitForIpcMessage();
    if (next === null) {
      deps.log('Close sentinel received, exiting grok loop');
      break;
    }
    prompt = next;
  }
}
